-- Autogenerated file. Changes may be lost!
return [[ [
    {
        "name": "Flush Two Pair",
        "desc": [
            "Two pairs with the same suit."
        ],
        "base_chips": 20.0,
        "base_mult": 4.0,
        "level_chips": 20.0,
        "level_mult": 2.0,
        "eval": [
            {
                "pattern": [
                    {
                        "rank": [
                            "A",
                            0
                        ],
                        "suit": [
                            "B",
                            false
                        ]
                    },
                    {
                        "rank": [
                            "A",
                            0
                        ],
                        "suit": [
                            "B",
                            false
                        ]
                    },
                    {
                        "rank": [
                            "X",
                            0
                        ],
                        "suit": [
                            "B",
                            false
                        ]
                    },
                    {
                        "rank": [
                            "X",
                            0
                        ],
                        "suit": [
                            "B",
                            false
                        ]
                    }
                ],
                "options": {}
            }
        ],
        "example": [
            {
                "rank": 6,
                "suit": "Hearts"
            },
            {
                "rank": 6,
                "suit": "Hearts"
            },
            {
                "rank": 12,
                "suit": "Hearts"
            },
            {
                "rank": 12,
                "suit": "Hearts"
            }
        ],
        "joker_mult": 12.0,
        "joker_chips": 100.0,
        "joker_xmult": 3.0,
        "joker_xmult_name": "The Double",
        "author": "TheLemon27"
    },
    
    {
        "name": "Two Flush Pair",
        "desc": [
            "A Pair of one suit",
            "and a Pair of another suit"
        ],
        "base_chips": 30.0,
        "base_mult": 2.0,
        "level_chips": 20.0,
        "level_mult": 2.0,
        "eval": [
            {
                "pattern": [
                    {
                        "rank": [
                            "a",
                            0
                        ],
                        "suit": [
                            "x",
                            false
                        ]
                    },
                    {
                        "rank": [
                            "a",
                            0
                        ],
                        "suit": [
                            "x",
                            false
                        ]
                    },
                    {
                        "rank": [
                            "b",
                            0
                        ],
                        "suit": [
                            "y",
                            false
                        ]
                    },
                    {
                        "rank": [
                            "b",
                            0
                        ],
                        "suit": [
                            "y",
                            false
                        ]
                    }
                ],
                "options": {}
            }
        ],
        "author": "NinjaBanana",
        "example": [
            {
                "rank": 7,
                "suit": "Diamonds"
            },
            {
                "rank": 7,
                "suit": "Diamonds"
            },
            {
                "rank": 2,
                "suit": "Spades"
            },
            {
                "rank": 2,
                "suit": "Spades"
            }
        ]
    }
] ]]